### ISSUE TITLE
TypeScript-Modules using `sass-variable-parser` won't build

### ISSUE THREAD

**Issue by neurolag** [mleg/sass-variable-parser#2]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
This module depends on `webpack` as it is imported in the [`index.ts`-file](https://github.com/mleg/sass-variable-parser/blob/master/src/index.ts#L2).  
Even though `webpack` has only been added to the `devDependencies`-list which causes all TypeScript-modules which depend on this module, `sass-variable-parser` to fail when building with following error:

```
node_modules/sass-variable-parser/build/main/index.d.ts:1:24 - error TS2307: Cannot find module 'webpack'.

1 import { loader } from 'webpack';
                         ~~~~~~~~~
```

Please add `webpack` to the normal `dependencies` to fix this issue.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by mleg** [comment]
Fixed.
Thanks for posting this issue.

**Comment by neurolag** [comment]
I just recognized that it's still not working properly.
`@types/webpack` must be added to the `dependencies`, too, in order to use it in the type-definitions.
